title = "Zionette Cleek"
baseURL = "https://cloud4z2.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[[deployment.targets]]
#An arbitrary name for this target.
name = "awsbucket"
URL = "s3://cloud4z2.com/?region=us-east-1"

[params]
address = "Tallahassee, FL"
email = "zionette@cloud4z2.awsapps.com"
favicon = "/favicon.ico"
firstName = "Zionette"
lastName = "Cleek"
phone = "1-850-324-6742"
profileImage = "img/IMG_2972.jpeg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showCertifications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.cloud4z2.slack.com/"
name = "Slack"

[[params.handles]]
link = "https://www.linkedin.com/in/zcleek/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/Zionette/"
name = "GitHub"

[[params.handles]]
link = "https://www.facebook.com/Cloud4z2-114631980341523"
name = "Facebook"



[[params.handles]]
link = "https://mewe.com/i/zionettecleek"
name = "MeWe"

[[params.handles]]
link = "https://www.reddit.com/user/ZionBot2"
name = "Reddit"



[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
